project:
  type: website
  output-dir: _site
  preview:
    port: 4321
    browser: true
  resources:
    - "assets/**"
  render:
    - "*.qmd"
    - "!*.md"
    - "!*.Rmd"
    - "!README.md"
    - "!LICENSE.md"
    - "!auxiliary/**"
    - "!assets/**" # i don't think we need stuff in this folder rendered, but not sure
execute:
  freeze: auto # when to re-run code during full project render
  cache: false
  echo: true
  keep-md: false
engines: ['knitr','julia']
format:
  html:
    # include-in-header:
      # - text: |
      #     <script> var MemberSpace = window.MemberSpace || {"subdomain":"datasciencerhealth"}; (function(d){ var s = d.createElement("script"); s.src = "https://cdn.memberspace.com/scripts/widgets.js"; var e = d.getElementsByTagName("script")[0]; e.parentNode.insertBefore(s,e); }(document)); </script>
    theme: 
      - materia  # bootstrap theme
      - brand    # specifications in brand.yml
      - assets/qspl-general.scss #more specifications in scss file
      - assets/qspl-slides.scss #formatting for slides
      - assets/qspl-unit-pages.scss #formatting for teaching units
      - assets/qspl-landing-pages.scss #formatting for landing pages
    css: assets/exams2forms-webex.css #this comes from the exam2forms package
    include-after-body: assets/exams2forms-webex.js # this comes from the exam2forms R package for quizzes    
    anchor-sections: true
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
    link-external-newwindow: true
    fig-align: center
    highlight-style: a11y
lightbox:
  desc-position: right
  match: auto
  effect: zoom
  loop: false
description-meta: "Short introductory courses that cover some modeling and data science tools."
website:
  title: "Modeling and Data Science Tools"
  description: "Short introductory courses that cover some modeling and data science tools."
  site-url: ""
  # favicon: /assets/images/qspl-logo.png
  # google-analytics: "UA-48442618-4"
  page-navigation: true
  cookie-consent: false    
  search: true
  navbar:
    pinned: true
    background: "#99ccff"
    # logo: /assets/images/qspl-logo.png
    # logo-alt: "QSPL logo"
    left:
      - text: "Courses"
        file: courses/courses.qmd
      - text: "About"
        file: pages/about.qmd
  sidebar:
    - id: fc1              # sidebar shown on all files it lists
      title: "Introduction to Positron"
      style: docked
      alignment: left
      collapse-level: 2
      contents: 
        - courses/fc1-intro-positron/intro-positron-overview.qmd
        - courses/fc1-intro-positron/positron-introduction/positron-introduction.qmd
        - courses/fc1-intro-positron/positron-install-setup/positron-install-setup.qmd
        - courses/fc1-intro-positron/positron-extensions/positron-extensions.qmd
        - courses/fc1-intro-positron/positron-features/positron-features.qmd
        - courses/fc1-intro-positron/positron-configuration/positron-configuration.qmd
        - courses/fc1-intro-positron/positron-use/positron-use.qmd
        - courses/fc1-intro-positron/positron-resources/positron-resources.qmd
    - id: fc2              # sidebar shown on all files it lists
      title: "Introduction to Quarto"
      style: docked
      alignment: left
      collapse-level: 2
      contents: 
        - courses/fc2-intro-quarto/intro-quarto-overview.qmd
        - courses/fc2-intro-quarto/quarto-introduction/quarto-introduction.qmd
        - courses/fc2-intro-quarto/quarto-install-setup/quarto-install-setup.qmd
        - courses/fc2-intro-quarto/quarto-positron/quarto-positron.qmd
        - courses/fc2-intro-quarto/quarto-use/quarto-use.qmd
        - courses/fc2-intro-quarto/quarto-resources/quarto-resources.qmd
  # page-footer:
    # left: |
    #   {{< fa regular copyright >}} QSP Library, 2025
   