project:
  type: website
  output-dir: _site
  preview:
    port: 4321
    browser: true
  resources:
    - "assets/**"
  render:
    - "*.qmd"
    - "!*.md"
    - "!*.Rmd"
    - "!README.md"
    - "!LICENSE.md"
    - "!auxiliary/**"
    - "!assets/**" # i don't think we need stuff in this folder rendered, but not sure
execute:
  freeze: auto # when to re-run code during full project render
  cache: false
  echo: true
  keep-md: false
engines: ['knitr','julia']
format:
  html:
    # include-in-header:
      # - text: |
      #     <script> var MemberSpace = window.MemberSpace || {"subdomain":"datasciencerhealth"}; (function(d){ var s = d.createElement("script"); s.src = "https://cdn.memberspace.com/scripts/widgets.js"; var e = d.getElementsByTagName("script")[0]; e.parentNode.insertBefore(s,e); }(document)); </script>
    theme: 
      - materia  # bootstrap theme
      - brand    # specifications in brand.yml
      - assets/general.scss #more specifications in scss file
      - assets/slides.scss #formatting for slides
      - assets/unit-pages.scss #formatting for teaching units
      - assets/landing-pages.scss #formatting for landing pages
    css: assets/exams2forms-webex.css #this comes from the exam2forms package
    include-after-body: assets/exams2forms-webex.js # from the exam2forms R package for quizzes    
    anchor-sections: true
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
    link-external-newwindow: true
    fig-align: center
    highlight-style: a11y
lightbox:
  desc-position: right
  match: auto
  effect: zoom
  loop: false
description-meta: "Short introductory courses that cover some modeling and data science tools."
website:
  title: "Modeling and Data Science Tools"
  description: "Short introductory courses that cover some modeling and data science tools."
  site-url: ""
  # favicon: /assets/images/qspl-logo.png
  # google-analytics: "UA-48442618-4"
  page-navigation: true
  cookie-consent: false    
  search: true
  navbar:
    pinned: true
    background: "#99ccff"
    # logo: /assets/images/qspl-logo.png
    # logo-alt: "QSPL logo"
    left:
      - text: "Courses"
        file: courses/courses.qmd
      # - text: "About"
      #   file: pages/about.qmd
  sidebar:
    - id: fc1              # sidebar shown on all files it lists
      title: "Introduction to Positron"
      style: floating 
      alignment: center
      collapse-level: 2
      contents: 
        - courses/fc1-intro-positron/intro-positron-toc.qmd
        - courses/fc1-intro-positron/positron-introduction/positron-introduction.qmd
        - courses/fc1-intro-positron/positron-install-setup/positron-install-setup.qmd
        - courses/fc1-intro-positron/positron-extensions/positron-extensions.qmd
        - courses/fc1-intro-positron/positron-features/positron-features.qmd
        - courses/fc1-intro-positron/positron-configuration/positron-configuration.qmd
        - courses/fc1-intro-positron/positron-use/positron-use.qmd
        - courses/fc1-intro-positron/positron-projects/positron-projects.qmd
        - courses/fc1-intro-positron/positron-resources/positron-resources.qmd
    - id: fc2a             # sidebar shown on all files it lists
      title: "Introduction to R"
      style: floating 
      alignment: center
      collapse-level: 2
      contents: 
        - courses/fc2a-intro-r/intro-r-toc.qmd
        - courses/fc2a-intro-r/r-introduction/r-introduction.qmd
        - courses/fc2a-intro-r/r-install-setup/r-install-setup.qmd
        - courses/fc2a-intro-r/r-positron/r-positron.qmd
        - courses/fc2a-intro-r/r-coding-basics/r-coding-basics.qmd
        - courses/fc2a-intro-r/r-packages/r-packages.qmd
        - courses/fc2a-intro-r/r-tidyverse/r-tidyverse.qmd
        - courses/fc2a-intro-r/r-further-resources/r-further-resources.qmd
    - id: fc3              # sidebar shown on all files it lists
      title: "Introduction to Quarto"
      style: floating
      alignment: center
      collapse-level: 2
      contents: 
        - courses/fc3-intro-quarto/intro-quarto-toc.qmd
        - courses/fc3-intro-quarto/quarto-introduction/quarto-introduction.qmd
        - courses/fc3-intro-quarto/quarto-install-setup/quarto-install-setup.qmd
        - courses/fc3-intro-quarto/quarto-positron/quarto-positron.qmd
        - courses/fc3-intro-quarto/quarto-basics/quarto-basics.qmd
        - courses/fc3-intro-quarto/quarto-beyond-basics/quarto-beyond-basics.qmd
        - courses/fc3-intro-quarto/quarto-resources/quarto-resources.qmd
    - id: fc4              # sidebar shown on all files it lists
      title: "Introduction to Git/GitHub"
      style: floating
      alignment: center
      collapse-level: 2
      contents: 
        - courses/fc4-intro-github/intro-github-toc.qmd
        - courses/fc4-intro-github/github-introduction/github-introduction.qmd
        - courses/fc4-intro-github/github-install-setup/github-install-setup.qmd
        - courses/fc4-intro-github/github-positron/github-positron.qmd
        - courses/fc4-intro-github/github-desktop/github-desktop.qmd
        - courses/fc4-intro-github/github-basic-use/github-basic-use.qmd
        - courses/fc4-intro-github/github-commits-branches/github-commits-branches.qmd
        - courses/fc4-intro-github/github-forks-prs/github-forks-prs.qmd
        - courses/fc4-intro-github/github-confidentiality/github-confidentiality.qmd
        - courses/fc4-intro-github/github-further-topics/github-further-topics.qmd
        - courses/fc4-intro-github/github-resources/github-resources.qmd
    - id: fc5              # sidebar shown on all files it lists
      title: "Introduction to AI Tools"
      style: floating
      alignment: center
      collapse-level: 2
      contents: 
        - courses/fc5-intro-ai/intro-ai-toc.qmd
        - courses/fc5-intro-ai/ai-introduction/ai-introduction.qmd
        - courses/fc5-intro-ai/ai-llm-introduction/ai-llm-introduction.qmd
        - courses/fc5-intro-ai/ai-tools/ai-tools.qmd
        - courses/fc5-intro-ai/ai-write-code-r/ai-write-code-r.qmd
        - courses/fc5-intro-ai/ai-fix-code-r/ai-fix-code-r.qmd
        - courses/fc5-intro-ai/ai-eda-r/ai-eda-r.qmd
        - courses/fc5-intro-ai/ai-analysis-r/ai-analysis-r.qmd
        - courses/fc5-intro-ai/ai-conceptual/ai-conceptual.qmd
        - courses/fc5-intro-ai/ai-resources/ai-resources.qmd
    - id: fc6              # sidebar shown on all files it lists
      title: "Portfolio Creation"
      style: floating
      alignment: center
      collapse-level: 2
      contents: 
        - courses/fc6-portfolio-creation/portfolio-creation-toc.qmd
        - courses/fc6-portfolio-creation/portfolio-introduction/portfolio-introduction.qmd
        - courses/fc6-portfolio-creation/portfolio-creation/portfolio-creation.qmd
  page-footer:
    left: |
      {{< fa regular copyright >}} The Authors, 2025
   
